### ISSUE TITLE
Add mongodb relation

### ISSUE THREAD

**Issue by justinmclark** [canonical/graylog-operator#10]
We will need similar changes for mongo as we needed for Elasticsearch. Use the changes in [this PR](https://github.com/canonical/graylog-operator/pull/9) as a guide.

More explicitly, we need:
1. `relation_changed` and `relation_broken` event observations and associated handlers
2. the mongodb uri to be pulled from the [mongodb charm relation](https://github.com/balbirthomas/mongodb-operator/tree/refactor)
3. the `mongodb_uri` to go into the `server.conf` mounted file in `_build_pod_spec()`
4. a property to tell us whether we have a mongo relation or not. If we have `has_elasticsearch` and `has_mongodb`, we can block the application if either of those are missing.

@Abuelodelanada, just let me know if you have any questions here.

**Comment by Abuelodelanada** [comment]
I'll take it!
